"""Initial migration

Revision ID: ac122fc04882
Revises: 
Create Date: 2024-08-16 17:18:06.444743

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac122fc04882'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observationDate', sa.Date(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('lastUpdate', sa.Date(), nullable=False),
    sa.Column('Confirmed', sa.Integer(), nullable=False),
    sa.Column('Recovered', sa.Integer(), nullable=False),
    sa.Column('Deaths', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__covid'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('covid')
    # ### end Alembic commands ###
