"""DeleteImports

Revision ID: a7e06da222e6
Revises: d6e878baf8d1
Create Date: 2024-08-15 20:57:34.367318

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e06da222e6'
down_revision: Union[str, None] = 'd6e878baf8d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('imports')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imports',
    sa.Column('import_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('import_id', name='pk__imports')
    )
    # ### end Alembic commands ###
