"""AddCovidStatistic

Revision ID: d6e878baf8d1
Revises: e3e31cdf6430
Create Date: 2024-08-15 20:54:51.418606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e878baf8d1'
down_revision: Union[str, None] = 'e3e31cdf6430'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('covid',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('observationDate', sa.Date(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('lastUpdate', sa.Date(), nullable=False),
    sa.Column('Confirmed', sa.Integer(), nullable=False),
    sa.Column('Recovered', sa.Integer(), nullable=False),
    sa.Column('Deaths', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__covid'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('covid')
    # ### end Alembic commands ###
